In [1]:
import numpy as np

In [2]:
A=np.array([[2,1,1],[-5,-3,0],[1,1,-1]])

In [14]:
b=np.array([[-1],[1],[-2]])

In [15]:
np.linalg.matrix_rank(A)

3

In [16]:
np.linalg.inv(A)

array([[-3., -2., -3.],
       [ 5.,  3.,  5.],
       [ 2.,  1.,  1.]])

In [17]:
x = np.dot(np.linalg.inv(A),b)

In [18]:
x

array([[  7.],
       [-12.],
       [ -3.]])

In [19]:
np.linalg.solve(A,b)

array([[  7.],
       [-12.],
       [ -3.]])

In [10]:
C=np.array([[2,1,1],[-5,-3,0],[1,1,-1],[0,5,-1]])
d=np.array([-1,1,-2,1])

In [11]:
np.linalg.matrix_rank(C)

3

In [13]:
np.linalg.solve(C,d)

LinAlgError: Last 2 dimensions of the array must be square