In [1]:
import pandas as pd
import numpy as np


In [2]:
data_df = pd.read_csv('marketing-campaign.csv')

In [3]:
data_df.head(2)

tv    web  radio  sales
0  0.916  1.689  0.208  1.204
1  9.359  1.706  1.071  4.800

In [9]:
# Build X1 and y matrix
def getX1andY(df,target_name):
    X = df.drop(target_name,axis=1).values
    y = data_df[target_name].values
    X1 = np.c_[np.ones(X.shape[0]),X]
    return (X1,y)

    
X1,y = getX1andY(data_df,'sales')

In [21]:
XX = np.matmul(X1.T,X1)
Xy = np.matmul(X1.T,y)
Xy

array([ 191.848   , 1369.170953,  426.802658,  291.543755])

In [24]:
w = np.matmul(np.linalg.inv(XX),Xy)
w

array([0.02487092, 0.39465146, 0.47037002, 0.30669954])

In [28]:
from scipy.linalg import lstsq

w, _,_,_ = lstsq(X1,y)
w

array([0.02487092, 0.39465146, 0.47037002, 0.30669954])