In [ ]:
import numpy as np

# The numpy array

In [ ]:
a1 = np.array([1,2,3])
a1

In [ ]:
a1.ndim

In [ ]:
a1.shape

In [ ]:
a2 = np.array([[1,2,3],[3,4,5]])
a2

In [ ]:
a2.ndim

In [ ]:
a2.shape

In [ ]:
a3 = np.array([1,2,3.3])

In [ ]:
a3.dtype

In [ ]:
a3 = np.array([1,2,3.3], dtype=int)
a3

In [ ]:
a4 = np.array([ ['f','l','a','k','e'],['s','n','a','k','e'],['a','w','a','k','e'] ])
a4.shape

In [ ]:
np.arange(0,15)

In [ ]:
np.arange(0,15,2)

In [ ]:
np.linspace(0,100,3, endpoint=False)

# Basic operatations with arrays

In [ ]:
a = np.arange(12)

In [ ]:
a.reshape(4,3)

In [ ]:
a.reshape(2,2,3)

In [ ]:
A = np.array( [[1,1], [0,1]] )
B = np.array( [[2,0], [3,4]] )

In [ ]:
A*B    

In [ ]:
a = np.array([11,22])
b = np.array([18,7,6])
c = np.array([1,3,5])
d = np.concatenate((a,b,c))
d

In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
np.concatenate((a, b), axis=0)

In [ ]:
np.concatenate((a, b), axis=1)

# Indexing

In [ ]:
a = np.reshape(np.arange(12),(4,3))
a

In [ ]:
a[0,0]

In [ ]:
a[3,0]

In [ ]:
a[1:3,0]

In [ ]:
a[:,2]

In [ ]:
a[0:4:2,0]

In [ ]:
a[0,0] = 5

In [ ]:
a

In [ ]:
b = np.array([[11, 22],[33, 44],[55, 66]])

In [ ]:
c = b.reshape((b.shape[0], b.shape[1], 1))

In [ ]:
c.shape

# Slicing

In [ ]:
a = np.arange(1,37).reshape(6,6)

In [ ]:
a

In [ ]:
a[:,1]

In [ ]:
a[0:2,4:6]

In [ ]:
a[5,4:]

In [ ]:
a[2::2, ::2]

# Boolean masking

In [ ]:
a = np.reshape(np.arange(12),(4,3))

In [ ]:
a>8

In [ ]:
a[a>8] = 0 

In [ ]:
a

# Broadcasting

In [ ]:
a = np.array([1,2,3])
a * 10

In [ ]:
np.array([ 1,  2,  3]) * np.array([10, 10, 10])

In [ ]:
a = np.array([[1], [2], [3], [4]])
b = np.array([10, 20, 30])

In [ ]:
a + b

In [ ]:
a = np.array([[1,2,3],[4,5,6]]) 
b = np.array([[1,2],[8,10],[3,12]]) 

In [ ]:
a.shape

In [ ]:
b.shape

# Exercise: distance to origin

In [ ]:
dist_to_origin = [0, 1498, 1063, 1968, 1498, 1758, 1469, 1472, 2230, 2391]

In [ ]:
dist = np.array(dist_to_origin)

In [ ]:
dist_T = dist.reshape(10,1)

In [ ]:
dist_matrix = np.abs(dist - dist_T)

In [ ]:
dist_matrix

# Copies and views

In [ ]:
a = np.arange(5)
a
# array([ 0,  1,  2,  3,  4])

In [ ]:
b = a # "a" and "b" are bound to the same array
b[0] = 5
a
# array([ 5,  1,  2,  3,  4])

In [ ]:
a = np.arange(10)
b = a[:2] # "b" is a narrower view of the array
b[0] = 10
a
# array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [ ]:
a = np.arange(10)
b = a.copy()[:2] # "b" is bound to a new array i.e. a copy of "a"
b[0] = 10
a
# array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a = np.arange(12)
b = a.reshape(3, 4) # reshape() returns a view of the array, but with a new shape
b
# array([[ 0,  1,  2,  3],
#        [ 4,  5,  6,  7],
#        [ 8,  9, 10, 11]])

In [ ]:
b[0] = 10 # changes the underlying data of both "a" and "b"
a
# array([10, 10, 10, 10,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
b
# array([[10, 10, 10, 10],
#        [ 4,  5,  6,  7],
#        [ 8,  9, 10, 11]])