In [1]:
import numpy as np

In [2]:
a = np.arange(1,37).reshape((6,6))
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [3]:
blue = a[:,1]
blue

array([ 2,  8, 14, 20, 26, 32])

In [4]:
yellow = a[0:2,-2:]
yellow

array([[ 5,  6],
       [11, 12]])

In [5]:
red = a[-1,-2:]
red

array([35, 36])

In [6]:
green = a[2:5:2,::2]
green

array([[13, 15, 17],
       [25, 27, 29]])