In [2]:
import numpy as np

# The numpy array

In [ ]:
a1 = np.array([1,2,3])
a1

In [ ]:
a1.ndim

In [ ]:
a1.shape

In [ ]:
a2 = np.array([[1,2,3],[3,4,5]])
a2

In [ ]:
a2.ndim

In [ ]:
a2.shape

In [ ]:
a3 = np.array([1,2,3.3])

In [ ]:
a3.dtype

In [ ]:
a3 = np.array([1,2,3.3], dtype=int)
a3

In [ ]:
a4 = np.array([ ['f','l','a','k','e'],['s','n','a','k','e'],['a','w','a','k','e'] ])
a4.shape

In [ ]:
np.arange(0,15)

In [ ]:
np.arange(0,15,2)

In [7]:
np.linspace(0,100,3, endpoint=False)

array([ 0.        , 33.33333333, 66.66666667])

# Basic operatations with arrays

In [ ]:
a = np.arange(12)

In [ ]:
a.reshape(4,3)

In [ ]:
a.reshape(2,2,3)

In [ ]:
A = np.array( [[1,1], [0,1]] )
B = np.array( [[2,0], [3,4]] )

In [ ]:
A*B    

In [ ]:
a = np.array([11,22])
b = np.array([18,7,6])
c = np.array([1,3,5])
d = np.concatenate((a,b,c))
d

In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
np.concatenate((a, b), axis=0)

In [ ]:
np.concatenate((a, b), axis=1)

# Indexing

In [8]:
a = np.reshape(np.arange(12),(4,3))
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [9]:
a[0,0]

0

In [10]:
a[3,0]

9

In [11]:
a[1:3,0]

array([3, 6])

In [12]:
a[:,2]

array([ 2,  5,  8, 11])

In [13]:
a[0:4:2,0]

array([0, 6])

In [14]:
a[0,0] = 5

In [15]:
a

array([[ 5,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [19]:
b = np.array([[11, 22],[33, 44],[55, 66]])
b

array([[11, 22],
       [33, 44],
       [55, 66]])

In [20]:
c = b.reshape((b.shape[0], b.shape[1], 1))
c

array([[[11],
        [22]],

       [[33],
        [44]],

       [[55],
        [66]]])

In [18]:
c.shape

(3, 2, 1)

# Slicing

In [ ]:
a = np.arange(1,37).reshape(6,6)

In [ ]:
a

In [ ]:
a[:,1]

In [ ]:
a[0:2,4:6]

In [ ]:
a[5,4:]

In [ ]:
a[2::2, ::2]

# Boolean masking

In [25]:
a = np.reshape(np.arange(12),(4,3))
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [22]:
a>8

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [ True,  True,  True]])

In [23]:
a[a>8] = 0 

In [24]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 0, 0]])

# Broadcasting

In [26]:
a = np.array([1,2,3])
a * 10

array([10, 20, 30])

In [27]:
np.array([ 1,  2,  3]) * np.array([10, 10, 10])

array([10, 20, 30])

In [31]:
a = np.array([[1], [2], [3], [4]])
b = np.array([10, 20, 30])
a
b

array([10, 20, 30])

In [29]:
a + b

array([[11, 21, 31],
       [12, 22, 32],
       [13, 23, 33],
       [14, 24, 34]])

In [34]:
a = np.array([[1,2,3],[4,5,6]]) 
b = np.array([[1,2],[8,10],[3,12]]) 
b

array([[ 1,  2],
       [ 8, 10],
       [ 3, 12]])

In [33]:
a.shape

(2, 3)

In [35]:
b.shape

(3, 2)

# Exercise: distance to origin

In [ ]:
dist_to_origin = [0, 1498, 1063, 1968, 1498, 1758, 1469, 1472, 2230, 2391]

In [ ]:
dist = np.array(dist_to_origin)

In [ ]:
dist_T = dist.reshape(10,1)

In [ ]:
dist_matrix = np.abs(dist - dist_T)

In [ ]:
dist_matrix

# Copies and views

In [ ]:
a = np.arange(5)
a
# array([ 0,  1,  2,  3,  4])

In [ ]:
b = a # "a" and "b" are bound to the same array
b[0] = 5
a
# array([ 5,  1,  2,  3,  4])

In [ ]:
a = np.arange(10)
b = a[:2] # "b" is a narrower view of the array
b[0] = 10
a
# array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [ ]:
a = np.arange(10)
b = a.copy()[:2] # "b" is bound to a new array i.e. a copy of "a"
b[0] = 10
a
# array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a = np.arange(12)
b = a.reshape(3, 4) # reshape() returns a view of the array, but with a new shape
b
# array([[ 0,  1,  2,  3],
#        [ 4,  5,  6,  7],
#        [ 8,  9, 10, 11]])

In [ ]:
b[0] = 10 # changes the underlying data of both "a" and "b"
a
# array([10, 10, 10, 10,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
b
# array([[10, 10, 10, 10],
#        [ 4,  5,  6,  7],
#        [ 8,  9, 10, 11]])